# version: '3'
# services:
#   hologram:
#     build: ./
#     container_name: hologram
#     ports:
#       - 3000:3000
#     networks:
#       - dejavu_db_network

# networks:
#   dejavu_db_network:


version: '3.7'

services:
  hologram:
    build: ./
    container_name: hologram
    restart: always
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    ports:
      - 3002:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  default:
    external:
      name: db_network