version: '3.7'

services:

  faust-radio:
    image: faust-radio
    #restart: no
    container_name: faust-radio
    build: ./
    ports:
      - 3011:3011

      
networks:
  default:
    external:
      name: my-net